### ISSUE TITLE
i followed the instructions now my game wont launch wtf

### ISSUE THREAD

**Issue by JFJ2** [Twingamerdudes/Lua-For-MPN#1]
i replaced that one Assembly-CSharp file with yours and i think that might've been a bad idea

**Comment by JFJ2** [comment]
i replaced that one Assembly-CSharp file with yours and i think that might've been a bad idea

**Comment by Twingamerdudes** [comment]
Did u also add the Moon Sharp DLL to ur managed folder too?

**Comment by JFJ2** [comment]
yep

**Comment by JFJ2** [comment]
maybe i wasnt supposed to copy paste the types folder??

**Comment by Twingamerdudes** [comment]
don't paste the types folder into the managed folder

**Comment by Twingamerdudes** [comment]
also, make sure your on the beta branch of M:PN, and have installed the latest version of Lua for M:PN

**Comment by JFJ2** [comment]
what does beta branch mean

**Comment by Twingamerdudes** [comment]
Right click M:PN in steam games list, go to Properties->Beta. Change "Beta Participation" to "releasebeta"

**Comment by JFJ2** [comment]
okay it launches like normal again

**Comment by Twingamerdudes** [comment]
now reinstall Lua for M:PN as switching to the beta branch overrided the install
